"""empty message

Revision ID: 4b20d71259a0
Revises: 7478fc47c79f
Create Date: 2024-06-17 16:51:04.527389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b20d71259a0'
down_revision: Union[str, None] = '7478fc47c79f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('signed_agreement_date', sa.Date(), nullable=True))
    op.drop_column('user', 'is_signed_agreement')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_signed_agreement', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'signed_agreement_date')
    # ### end Alembic commands ###
