"""empty message

Revision ID: 7478fc47c79f
Revises: fc3793693767
Create Date: 2024-06-17 11:10:52.408380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7478fc47c79f'
down_revision: Union[str, None] = 'fc3793693767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_signed_agreement', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_signed_agreement')
    # ### end Alembic commands ###
