name: Build and publish manually

on: [push]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t vm .
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Tag image
        run: docker tag vm ${{ secrets.CONTAINER_REGISTRY }}/pb_portal:latest
      - name: Push image to DO Container Registry
        run: docker push ${{ secrets.CONTAINER_REGISTRY }}/pb_portal:latest
